export const INIT_GET_PLAYERS = 'INIT_GET_PLAYERS';

export const GET_PLAYERS_REQUEST = 'GET_PLAYERS_REQUEST';
export const GET_PLAYERS_SUCCESS = 'GET_PLAYERS_SUCCESS';
export const GET_PLAYERS_FAILURE = 'GET_PLAYERS_FAILURE';

export const GET_PLAYER_DETAILS_SUCCESS = 'GET_PLAYER_DETAILS_SUCCESS';
export const GET_PLAYER_DETAILS_FAILURE = 'GET_PLAYER_DETAILS_FAILURE';

export const GET_PLAYER_STATS_SUCCESS = 'GET_PLAYER_STATS_SUCCESS';
export const GET_PLAYER_STATS_FAILURE = 'GET_PLAYER_STATS_FAILURE';

export const GET_TEAMS_SUCCESS = 'GET_TEAMS_SUCCESS';
export const GET_TEAMS_FAILURE = 'GET_TEAMS_FAILURE';

export const GET_POSITIONS_SUCCESS = 'GET_POSITIONS_SUCCESS';
export const GET_POSITIONS_FAILURE = 'GET_POSITIONS_FAILURE';
